### ISSUE TITLE
Remove docker usage

### ISSUE THREAD

**Issue by dominikholler** [kubevirt/containerdisks#5]
All usage of docker should be replaced by podman.

**Comment by usrbinkat** [comment]
I would like to politely open this decision up for discussion.

Podman and buildah are opinionated Red Hat products whereas Kubevirt is, as I understand, a wider community project.

Further, podman and buildah do not offer the advanced workflows of docker `buildx bake` at this time which was a workflow my project has been refining to support efficient image building that scales simply across architectures, distributions, and versions.

As an aggressive Kubevirt dependent project maintainer I hoped to begin upstreaming image build pipelines to the containerdisks repository. Until podman and buildah meet or exceed the elegance of docker buildx bake, I worry that eliminating the most maintainable and scalable path to disk image publishing in this manner could alienate a key community building opportunity.

**Comment by rmohr** [comment]
> I would like to politely open this decision up for discussion.
> 
> Podman and buildah are opinionated Red Hat products whereas Kubevirt is, as I understand, a wider community project.
> 
> Further, podman and buildah do not offer the advanced workflows of docker `buildx bake` at this time which was a workflow my project has been refining to support efficient image building that scales simply across architectures, distributions, and versions.

At least for me the main motivation on why to get rid of docker is that it is hard to use it inside docker/podman (dind) due to its daemon approach and for CI efficiency (where the community does not have endless resources) we finally need the switch to being able to efficiently share "local" container registries as well as running our docker-in-docker builds with less privileges.

What I normally try to do is using build options which are compatible between podman and docker (but that probably eliminates what you would want to make advantage of).

> 
> As an aggressive Kubevirt dependent project maintainer I hoped to begin upstreaming image build pipelines to the containerdisks repository. Until podman and buildah meet or exceed the elegance of docker buildx bake, I worry that eliminating the most maintainable and scalable path to disk image publishing in this manner could alienate a key community building opportunity.


Looking forward to see what you are building and how you do that :)



> 
> I propose resolving #7 before continuing with this discussion and action.

That sounds great :+1: Thanks for filing it.

**Comment by rmohr** [comment]
@usrbinkat took your hint regarding to go-containerregistry in slack and implemented it in #8 . It can do everything without any container runtime involved at all. Happy to get some feedback :)

**Comment by usrbinkat** [comment]
Awesome! Love it!

**Comment by rmohr** [comment]
/close

#8 is in which removes the need for any container runtime :)
