### ISSUE TITLE
ARM containerdisks

### ISSUE THREAD

**Issue by codingben** [kubevirt/containerdisks#80]
Produce ARM community containerdisks that are based on Fedora or CentOS and published in Quay [1].

[1] https://quay.io/organization/containerdisks

**Comment by zhlhahaha** [comment]
Typically, we conduct the build process and release process for images across all CPU architectures on x86_64 systems. This approach offers several advantages:

- It simplifies the control over the build process, enabling the straightforward creation of multi-architecture images and their corresponding manifests.
- Building images on different machines complicates the process of obtaining each image's sha256sum, which is essential for generating multi-architecture manifests.

As far as I see, we need tackle two issues before we can make it support multi-arch images:

1. Add CPU arch related VM source. Currently, I can only see x86_64 image source. https://github.com/kubevirt/containerdisks/blob/adba1480e0a92ad4ffc48a251e22788bc756e6b7/artifacts/centos/centos.go#L149-L158
2. Enable to build multi-arch container images and then generate multi-arch manifest for them.

In terms of CI, there are two main configuration files for the project.

- https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
- https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml

In the files, there three tests:

- `make test`  use to lint and ginkgo test for medius
- `build.sh -b` use to verify if medius can successfully build images
- `pipeline.sh/pipeline-periodic.sh` use to verify if the new generated images can successfully boot in a KubeVirt cluster

Regarding the CI lane for Arm64, from my perspective, the primary requirement is to verify whether the cross-built image can successfully boot on an Arm64 KubeVirt cluster. Users typically obtain the image from https://quay.io/organization/containerdisks rather than building it themselves. Therefore, setting up a periodic job might be the optimal solution. 

Currently, there is a periodic job in place, but it employs a native-build approach to construct images, which are then tested in a VM-based KubeVirt cluster. This method does not suit our scenario.

**Comment by zhlhahaha** [comment]
cc: @andreabolognani @dhiller

**Comment by codingben** [comment]
This issue will be opened until we'll merge #84 - to add arm64 artifacts (Fedora, CentOS, etc).

**Comment by 0xFelix** [comment]
Fixed by #84

**Comment by 0xFelix** [comment]
@andreabolognani Please also thank @codingben and @lyarwood for making it happen! :)

**Comment by zhlhahaha** [comment]
Great work, thank @0xFelix @codingben @lyarwood !
